### ISSUE TITLE
Enlist on made-in-africa

### ISSUE THREAD

**Issue by alphaolomi** [MadeInKenya/madeinkenya.github.io#34]
Hello,

Nice work here 👏🏾 

Kindly consider enlisting on [made-in-africa](https://github.com/FotieMConstant/made-in-africa)

Thanks

**Comment by alphaolomi** [comment]
See https://github.com/FotieMConstant/made-in-africa/issues/3

**Comment by alphaolomi** [comment]
Hello everyone

Enlisted already ✅ 

Thank you

**Comment by JacksiroKe** [comment]
Hello @alphaolomi sorry we may have gotten busy to enlist it there, personally i was away the whole weekend. Good to see your amazing work out there
