### ISSUE TITLE
Include dev wiki/doc

### ISSUE THREAD

**Issue by marvinhosea** [MadeInKenya/madeinkenya.github.io#5]
Add development wiki or document stating the frameworks used and development guidelines to help other developers to contribute.

**Comment by tamzi** [comment]
Can update with ReadMe master templates

**Comment by marvinhosea** [comment]
Yeah exactly. @danvick and @JacksiroKe can we bring this project to life??

**Comment by JacksiroKe** [comment]
yeah  @danvick and I are already working on some awesome stuff. @tamzi  Dan is working on what you mentioned and myself am on the website

**Comment by marvinhosea** [comment]
Awesome stuff? Can you use GitHub project or issues to create tasks or pending todos and tech wiki to allow other developers to contribute ama hii tunaenda na yesu. You can close this issue with reference to the doc commit.

**Comment by marvinhosea** [comment]
You can include the development stack too

**Comment by JacksiroKe** [comment]
thanks at Marvin for the awesome ideas bado we were just getting started. we a new issue on receiving new ideas please check it out.

**Comment by tamzi** [comment]
i dont think this is solved yet
